// Thin fr/en wrapper around the fr/en/ja dataset in pokemon-names.json
// (generated by scripts/generate-pokemon-names.ts). Kept as a separate module
// because most callers only need fr/en and the `getPokemonName` helper.
import raw from './pokemon-names.json';

export interface PokemonNameEntry {
  fr: string;
  en: string;
}

const source = raw as Record<string, { fr: string; en: string; ja: string }>;

export const POKEMON_NAMES: Readonly<Record<number, PokemonNameEntry>> = Object.fromEntries(
  Object.entries(source).map(([n, { fr, en }]) => [n, { fr, en }]),
);

/** Fallback to French, then English, then `???`. */
export function getPokemonName(n: number, lang: 'fr' | 'en' = 'fr'): string {
  return POKEMON_NAMES[n]?.[lang] ?? '???';
}
