/**
 * Fetches Pokémon names (French + English) from PokeAPI for all 1025 Pokémon.
 * Writes a static dataset to lib/data/pokemon-names.ts.
 *
 * Usage: npx tsx scripts/fetch-pokemon-names.ts
 */

import fs from 'fs';
import path from 'path';

const TOTAL_POKEMON = 1025;
const BATCH_SIZE = 25;
const OUTPUT_PATH = path.join(
  __dirname,
  '..',
  'lib',
  'data',
  'pokemon-names.ts'
);

interface PokeAPIName {
  name: string;
  language: {
    name: string;
  };
}

interface PokeAPISpeciesResponse {
  names: PokeAPIName[];
}

interface PokemonNameEntry {
  fr: string;
  en: string;
}

async function fetchPokemonNames(id: number): Promise<PokemonNameEntry> {
  try {
    const response = await fetch(
      `https://pokeapi.co/api/v2/pokemon-species/${id}`
    );

    if (!response.ok) {
      console.warn(`⚠️  Failed to fetch #${id}: HTTP ${response.status}`);
      return { fr: 'Inconnu', en: 'Unknown' };
    }

    const data: PokeAPISpeciesResponse = await response.json();

    const frName = data.names.find((n) => n.language.name === 'fr')?.name;
    const enName = data.names.find((n) => n.language.name === 'en')?.name;

    if (!frName || !enName) {
      console.warn(
        `⚠️  Missing translations for #${id}: fr=${frName}, en=${enName}`
      );
      return {
        fr: frName || 'Inconnu',
        en: enName || 'Unknown',
      };
    }

    return { fr: frName, en: enName };
  } catch (error) {
    console.warn(`⚠️  Error fetching #${id}:`, error);
    return { fr: 'Inconnu', en: 'Unknown' };
  }
}

async function main() {
  console.log(`📦 Fetching ${TOTAL_POKEMON} Pokémon names from PokeAPI...`);

  const allNames: Record<number, PokemonNameEntry> = {};

  for (let start = 1; start <= TOTAL_POKEMON; start += BATCH_SIZE) {
    const end = Math.min(start + BATCH_SIZE - 1, TOTAL_POKEMON);
    const batch = Array.from({ length: end - start + 1 }, (_, i) => start + i);

    const results = await Promise.all(batch.map(fetchPokemonNames));

    batch.forEach((id, idx) => {
      allNames[id] = results[idx];
    });

    if (start % 100 === 1 || end === TOTAL_POKEMON) {
      console.log(`✓ Fetched #${start}-${end}`);
    }
  }

  // Generate the TypeScript file
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/fetch-pokemon-names.ts — DO NOT EDIT BY HAND',
    '// Source: PokeAPI /pokemon-species/{n}, regenerate with `npx tsx scripts/fetch-pokemon-names.ts`',
    '',
    'export interface PokemonNameEntry {',
    '  fr: string;',
    '  en: string;',
    '}',
    '',
    'export const POKEMON_NAMES: Readonly<Record<number, PokemonNameEntry>> = {',
  ];

  for (let id = 1; id <= TOTAL_POKEMON; id++) {
    const entry = allNames[id];
    const comma = id < TOTAL_POKEMON ? ',' : '';
    lines.push(
      `  ${id}: { fr: '${entry.fr}', en: '${entry.en}' }${comma}`
    );
  }

  lines.push('};');
  lines.push('');
  lines.push('/** Fallback to French, then English, then `???`. */');
  lines.push(
    "export function getPokemonName(n: number, lang: 'fr' | 'en' = 'fr'): string {"
  );
  lines.push("  return POKEMON_NAMES[n]?.[lang] ?? '???';");
  lines.push('}');
  lines.push('');

  fs.writeFileSync(OUTPUT_PATH, lines.join('\n'));

  const failCount = Object.values(allNames).filter(
    (e) => e.fr === 'Inconnu' || e.en === 'Unknown'
  ).length;

  console.log(`\n✅ Written ${TOTAL_POKEMON} entries to ${OUTPUT_PATH}`);
  if (failCount > 0) {
    console.log(`⚠️  ${failCount} entries used fallback values`);
  }
}

main().catch((error) => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
